export default {
    'title_web': 'xcoders - course web',
    'navbar_title': 'XcodersJS',
    'sidebar_title': 'xcoders teams',
    'footer_title': 'xcodersJS teams, Inc.',
    'copyright': 'Farhannnn',
    'user': {
        'email': 'farhanxcode7@gmail.com',
        'github': 'Fxc7',
        // if you don't have an account, just leave it blank.
        'whatsapp': '6285956396417',
        'instagram': 'farhanxcode7',
        'facebook': 'FarhanXCode7',
        'twitter': 'FarhanXCode7',
        'youtube': '@FarhanXCode7',
        'linkedin': 'farhanxcode7',
    },
    'navLinks': [
        {
            'id': 1,
            'path': "",
            'text': "Home",
        },
        {
            'id': 2,
            'path': "classes",
            'text': "Classes",
        },
        {
            'id': 3,
            'path': "testimonial",
            'text': "Testimonial",
        },
        {
            'id': 4,
            'path': "faq",
            'text': "FAQ",
        },
        {
            'id': 5,
            'path': "terms",
            'text': "Terms And Conditions",
        },
    ],
    'allClass': [
        {
            id: 1,
            image: "/images/class/class-1.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Character Illustration with Adobe Illustrator",
            price: "Rp. 300.000",
            buy: "Buy Class",
            delay: "1300",
        },
        {
            id: 2,
            image: "/images/class/class-2.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "UI UX Website Design for Beginner with Figma",
            price: "Rp. 340.000",
            buy: "Buy Class",
            delay: "1600",
        },
        {
            id: 3,
            image: "/images/class/class-3.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Web Developer Bootstrap 5",
            price: "Rp. 280.000",
            buy: "Buy Class",
            delay: "1900",
        },
        {
            id: 4,
            image: "/images/class/class-4.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Logo with Adobe Illustrator",
            price: "Rp. 420.000",
            buy: "Buy Class",
            delay: "",
        },
        {
            id: 5,
            image: "/images/class/class-5.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "3D Modelling for Beginner with 3D Blender",
            price: "Rp. 380.000",
            buy: "Buy Class",
            delay: "300",
        },
        {
            id: 6,
            image: "/images/class/class-6.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Icon Design with Adobe Illustrator",
            price: "Rp. 300.000",
            buy: "Buy Class",
            delay: "600",
        },
        {
            id: 7,
            image: "/images/class/class-7.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Design Vektor with Corel Draw CC for Beginner",
            price: "Rp. 340.000",
            buy: "Buy Class",
            delay: "",
        },
        {
            id: 8,
            image: "/images/class/class-8.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "UI UX Design with Adobe XD for Beginner",
            price: "Rp. 400.000",
            buy: "Buy Class",
            delay: "300",
        },
        {
            id: 9,
            image: "/images/class/class-9.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Mastering Mobile Developer with Flutter",
            price: "Rp. 320.000",
            buy: "Buy Class",
            delay: "600",
        },
        {
            id: 10,
            image: "/images/class/class-10.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Fullstack ReactJS XD For Beginner",
            price: "Rp. 390.000",
            buy: "Buy Class",
            delay: "",
        },
        {
            id: 11,
            image: "/images/class/class-11.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Master of Applied Data Science for Beginner",
            price: "Rp. 540.000",
            buy: "Buy Class",
            delay: "300",
        },
        {
            id: 12,
            image: "/images/class/class-12.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Master of Computer and Information Technology for Beginner",
            price: "Rp. 700.000",
            buy: "Buy Class",
            delay: "600",
        }
    ],
    'ClassNew': [
        {
            id: 1,
            image: "/images/class/class-1.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star-half-stroke",
            title: "Character Illustration with Adobe Illustrator",
            price: "Rp. 300.000",
            buy: "Buy Class",
            delay: "200",
        },
        {
            id: 2,
            image: "/images/class/class-2.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "UI UX Website Design for Beginner with Figma",
            price: "Rp. 340.000",
            buy: "Buy Class",
            delay: "300",
        },
        {
            id: 3,
            image: "/images/class/class-3.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Web Developer Bootstrap 5",
            price: "Rp. 280.000",
            buy: "Buy Class",
            delay: "400",
        },
        {
            id: 4,
            image: "/images/class/class-4.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Logo with Adobe Illustrator",
            price: "Rp. 420.000",
            buy: "Buy Class",
            delay: "200",
        },
        {
            id: 5,
            image: "/images/class/class-5.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "3D Modelling for Beginner with 3D Blender",
            price: "Rp. 380.000",
            buy: "Buy Class",
            delay: "300",
        },
        {
            id: 6,
            image: "/images/class/class-6.jpg",
            star1: "fa-solid fa-star",
            star2: "fa-solid fa-star",
            star3: "fa-solid fa-star",
            star4: "fa-solid fa-star",
            star5: "fa-solid fa-star",
            title: "Mastering Icon Design with Adobe Illustrator",
            price: "Rp. 300.000",
            buy: "Buy Class",
            delay: "400",
        }
    ],
    'testimonial': [
        {
            id: 1,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-1.jpg",
            name: "People 1",
            skill: "UI UX Designer",
        },
        {
            id: 2,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-2.jpg",
            name: "People 2",
            skill: "Flutter Developer",
        },
        {
            id: 3,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-3.jpg",
            name: "People 3",
            skill: "Web Developer",
        },
        {
            id: 4,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-1.jpg",
            name: "People 4",
            skill: "UI UX Designer",
        },
        {
            id: 5,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-2.jpg",
            name: "People 5",
            skill: "Flutter Developer",
        },
        {
            id: 6,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-3.jpg",
            name: "People 6",
            skill: "Web Developer",
        },
        {
            id: 7,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-1.jpg",
            name: "People 7",
            skill: "UI UX Designer",
        },
        {
            id: 8,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-2.jpg",
            name: "People 8",
            skill: "Flutter Developer",
        },
        {
            id: 9,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-3.jpg",
            name: "People 9",
            skill: "Web Developer",
        },
    ],
    'dataSwiper': [
        {
            id: 1,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-1.jpg",
            name: "People 1",
            skill: "UI UX Designer",
        },
        {
            id: 2,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-2.jpg",
            name: "People 2",
            skill: "Flutter Developer",
        },
        {
            id: 3,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-3.jpg",
            name: "People 3",
            skill: "Web Developer",
        },
        {
            id: 4,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-1.jpg",
            name: "People 4",
            skill: "UI UX Designer",
        },
        {
            id: 5,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-2.jpg",
            name: "People 5",
            skill: "Flutter Developer",
        },
        {
            id: 6,
            desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor, saepe a. Quod eos non, dolores sapiente dicta quam esse reprehenderit explicabo vitae nesciunt ut laborum harum, vel optio corporis voluptatem?",
            image: "/images/testimonial/people-3.jpg",
            name: "People 6",
            skill: "Web Developer",
        },
    ],
    'faq': [
        {
            id: 1,
            eventKey: 0,
            title: "Is this a Subscription?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 2,
            eventKey: 1,
            title: "How is the Learning System?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 3,
            eventKey: 2,
            title: "Can I Share It with Others?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 4,
            eventKey: 3,
            title: "Is There a Discussion Group?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 5,
            eventKey: 4,
            title: "Is it Accessible Forever?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 6,
            eventKey: 5,
            title: "Are There Any Mentors?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 7,
            eventKey: 6,
            title: "Can I Download the Videos?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
        {
            id: 8,
            eventKey: 7,
            title: "Can I Change Classes after Purchasing?",
            desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id estlaborum.",
        },
    ]
};